// source: vm0049.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var verraCcsExtensionSet_pb = require('./verraCcsExtensionSet_pb.js');
goog.object.extend(proto, verraCcsExtensionSet_pb);
goog.exportSymbol('proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass', null, global);
goog.exportSymbol('proto.verra.ccs.extensionSet.modules.vm0049.VariableReading', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.repeatedFields_, null);
};
goog.inherits(proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.displayName = 'proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.displayName = 'proto.verra.ccs.extensionSet.modules.vm0049.VariableReading';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.repeatedFields_ = [2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.toObject = function(opt_includeInstance) {
  return proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.toObject = function(includeInstance, msg) {
  var f, obj = {
percentCo2Mass: (f = msg.getPercentCo2Mass()) && verraCcsExtensionSet_pb.DoubleValue.toObject(includeInstance, f),
mCO2ReadingsList: jspb.Message.toObjectList(msg.getMCO2ReadingsList(),
    proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject, includeInstance),
xCO2ReadingsList: jspb.Message.toObjectList(msg.getXCO2ReadingsList(),
    proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject, includeInstance),
mKReadingsList: jspb.Message.toObjectList(msg.getMKReadingsList(),
    proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject, includeInstance),
xKReadingsList: jspb.Message.toObjectList(msg.getXKReadingsList(),
    proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass;
  return proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new verraCcsExtensionSet_pb.DoubleValue;
      reader.readMessage(value,verraCcsExtensionSet_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPercentCo2Mass(value);
      break;
    case 2:
      var value = new proto.verra.ccs.extensionSet.modules.vm0049.VariableReading;
      reader.readMessage(value,proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader);
      msg.addMCO2Readings(value);
      break;
    case 3:
      var value = new proto.verra.ccs.extensionSet.modules.vm0049.VariableReading;
      reader.readMessage(value,proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader);
      msg.addXCO2Readings(value);
      break;
    case 4:
      var value = new proto.verra.ccs.extensionSet.modules.vm0049.VariableReading;
      reader.readMessage(value,proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader);
      msg.addMKReadings(value);
      break;
    case 5:
      var value = new proto.verra.ccs.extensionSet.modules.vm0049.VariableReading;
      reader.readMessage(value,proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader);
      msg.addXKReadings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPercentCo2Mass();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      verraCcsExtensionSet_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getMCO2ReadingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter
    );
  }
  f = message.getXCO2ReadingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter
    );
  }
  f = message.getMKReadingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter
    );
  }
  f = message.getXKReadingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter
    );
  }
};


/**
 * optional verra.ccs.extensionSet.DoubleValue percent_co2_mass = 1;
 * @return {?proto.verra.ccs.extensionSet.DoubleValue}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.getPercentCo2Mass = function() {
  return /** @type{?proto.verra.ccs.extensionSet.DoubleValue} */ (
    jspb.Message.getWrapperField(this, verraCcsExtensionSet_pb.DoubleValue, 1));
};


/**
 * @param {?proto.verra.ccs.extensionSet.DoubleValue|undefined} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.setPercentCo2Mass = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.clearPercentCo2Mass = function() {
  return this.setPercentCo2Mass(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.hasPercentCo2Mass = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated VariableReading m_c_o_2_readings = 2;
 * @return {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.getMCO2ReadingsList = function() {
  return /** @type{!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, 2));
};


/**
 * @param {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.setMCO2ReadingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading=} opt_value
 * @param {number=} opt_index
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.addMCO2Readings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.clearMCO2ReadingsList = function() {
  return this.setMCO2ReadingsList([]);
};


/**
 * repeated VariableReading x_c_o_2_readings = 3;
 * @return {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.getXCO2ReadingsList = function() {
  return /** @type{!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, 3));
};


/**
 * @param {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.setXCO2ReadingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading=} opt_value
 * @param {number=} opt_index
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.addXCO2Readings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.clearXCO2ReadingsList = function() {
  return this.setXCO2ReadingsList([]);
};


/**
 * repeated VariableReading m_k_readings = 4;
 * @return {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.getMKReadingsList = function() {
  return /** @type{!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, 4));
};


/**
 * @param {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.setMKReadingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading=} opt_value
 * @param {number=} opt_index
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.addMKReadings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.clearMKReadingsList = function() {
  return this.setMKReadingsList([]);
};


/**
 * repeated VariableReading x_k_readings = 5;
 * @return {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.getXKReadingsList = function() {
  return /** @type{!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, 5));
};


/**
 * @param {!Array<!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading>} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.setXKReadingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading=} opt_value
 * @param {number=} opt_index
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.addXKReadings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.verra.ccs.extensionSet.modules.vm0049.VariableReading, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.Formula3PercentCo2Mass.prototype.clearXKReadingsList = function() {
  return this.setXKReadingsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.toObject = function(opt_includeInstance) {
  return proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.toObject = function(includeInstance, msg) {
  var f, obj = {
checkpointId: jspb.Message.getFieldWithDefault(msg, 1, ""),
checkpointVariableId: jspb.Message.getFieldWithDefault(msg, 2, ""),
variableTemplateId: jspb.Message.getFieldWithDefault(msg, 3, ""),
variableTemplateVersion: jspb.Message.getFieldWithDefault(msg, 4, ""),
variableValue: (f = msg.getVariableValue()) && verraCcsExtensionSet_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.verra.ccs.extensionSet.modules.vm0049.VariableReading;
  return proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCheckpointId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCheckpointVariableId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVariableTemplateId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVariableTemplateVersion(value);
      break;
    case 5:
      var value = new verraCcsExtensionSet_pb.DoubleValue;
      reader.readMessage(value,verraCcsExtensionSet_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setVariableValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCheckpointId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCheckpointVariableId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVariableTemplateId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getVariableTemplateVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getVariableValue();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      verraCcsExtensionSet_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string checkpoint_id = 1;
 * @return {string}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.getCheckpointId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.setCheckpointId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string checkpoint_variable_id = 2;
 * @return {string}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.getCheckpointVariableId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.setCheckpointVariableId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string variable_template_id = 3;
 * @return {string}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.getVariableTemplateId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.setVariableTemplateId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string variable_template_version = 4;
 * @return {string}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.getVariableTemplateVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.setVariableTemplateVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional verra.ccs.extensionSet.DoubleValue variable_value = 5;
 * @return {?proto.verra.ccs.extensionSet.DoubleValue}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.getVariableValue = function() {
  return /** @type{?proto.verra.ccs.extensionSet.DoubleValue} */ (
    jspb.Message.getWrapperField(this, verraCcsExtensionSet_pb.DoubleValue, 5));
};


/**
 * @param {?proto.verra.ccs.extensionSet.DoubleValue|undefined} value
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
*/
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.setVariableValue = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.verra.ccs.extensionSet.modules.vm0049.VariableReading} returns this
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.clearVariableValue = function() {
  return this.setVariableValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.verra.ccs.extensionSet.modules.vm0049.VariableReading.prototype.hasVariableValue = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.verra.ccs.extensionSet.modules.vm0049);
