// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vm0049.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Verra.Ccs.ExtensionSet.Modules.Vm0049 {

  /// <summary>Holder for reflection information generated from vm0049.proto</summary>
  public static partial class Vm0049Reflection {

    #region Descriptor
    /// <summary>File descriptor for vm0049.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Vm0049Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgx2bTAwNDkucHJvdG8SJXZlcnJhLmNjcy5leHRlbnNpb25TZXQubW9kdWxl",
            "cy52bTAwNDkaGnZlcnJhQ2NzRXh0ZW5zaW9uU2V0LnByb3RvIpcDChZGb3Jt",
            "dWxhM1BlcmNlbnRDbzJNYXNzEj0KEHBlcmNlbnRfY28yX21hc3MYASABKAsy",
            "Iy52ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0LkRvdWJsZVZhbHVlElAKEG1fY19v",
            "XzJfcmVhZGluZ3MYAiADKAsyNi52ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0Lm1v",
            "ZHVsZXMudm0wMDQ5LlZhcmlhYmxlUmVhZGluZxJQChB4X2Nfb18yX3JlYWRp",
            "bmdzGAMgAygLMjYudmVycmEuY2NzLmV4dGVuc2lvblNldC5tb2R1bGVzLnZt",
            "MDA0OS5WYXJpYWJsZVJlYWRpbmcSTAoMbV9rX3JlYWRpbmdzGAQgAygLMjYu",
            "dmVycmEuY2NzLmV4dGVuc2lvblNldC5tb2R1bGVzLnZtMDA0OS5WYXJpYWJs",
            "ZVJlYWRpbmcSTAoMeF9rX3JlYWRpbmdzGAUgAygLMjYudmVycmEuY2NzLmV4",
            "dGVuc2lvblNldC5tb2R1bGVzLnZtMDA0OS5WYXJpYWJsZVJlYWRpbmcixgEK",
            "D1ZhcmlhYmxlUmVhZGluZxIVCg1jaGVja3BvaW50X2lkGAEgASgJEh4KFmNo",
            "ZWNrcG9pbnRfdmFyaWFibGVfaWQYAiABKAkSHAoUdmFyaWFibGVfdGVtcGxh",
            "dGVfaWQYAyABKAkSIQoZdmFyaWFibGVfdGVtcGxhdGVfdmVyc2lvbhgEIAEo",
            "CRI7Cg52YXJpYWJsZV92YWx1ZRgFIAEoCzIjLnZlcnJhLmNjcy5leHRlbnNp",
            "b25TZXQuRG91YmxlVmFsdWVCUQoldmVycmEuY2NzLmV4dGVuc2lvblNldC5t",
            "b2R1bGVzLnZtMDA0OVABqgIlVmVycmEuQ2NzLkV4dGVuc2lvblNldC5Nb2R1",
            "bGVzLlZtMDA0OWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Verra.Ccs.ExtensionSet.VerraCcsExtensionSetReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Verra.Ccs.ExtensionSet.Modules.Vm0049.Formula3PercentCo2Mass), global::Verra.Ccs.ExtensionSet.Modules.Vm0049.Formula3PercentCo2Mass.Parser, new[]{ "PercentCo2Mass", "MCO2Readings", "XCO2Readings", "MKReadings", "XKReadings" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading), global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading.Parser, new[]{ "CheckpointId", "CheckpointVariableId", "VariableTemplateId", "VariableTemplateVersion", "VariableValue" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Formula3PercentCo2Mass : pb::IMessage<Formula3PercentCo2Mass>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Formula3PercentCo2Mass> _parser = new pb::MessageParser<Formula3PercentCo2Mass>(() => new Formula3PercentCo2Mass());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Formula3PercentCo2Mass> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Verra.Ccs.ExtensionSet.Modules.Vm0049.Vm0049Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Formula3PercentCo2Mass() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Formula3PercentCo2Mass(Formula3PercentCo2Mass other) : this() {
      percentCo2Mass_ = other.percentCo2Mass_ != null ? other.percentCo2Mass_.Clone() : null;
      mCO2Readings_ = other.mCO2Readings_.Clone();
      xCO2Readings_ = other.xCO2Readings_.Clone();
      mKReadings_ = other.mKReadings_.Clone();
      xKReadings_ = other.xKReadings_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Formula3PercentCo2Mass Clone() {
      return new Formula3PercentCo2Mass(this);
    }

    /// <summary>Field number for the "percent_co2_mass" field.</summary>
    public const int PercentCo2MassFieldNumber = 1;
    private global::Verra.Ccs.ExtensionSet.DoubleValue percentCo2Mass_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Verra.Ccs.ExtensionSet.DoubleValue PercentCo2Mass {
      get { return percentCo2Mass_; }
      set {
        percentCo2Mass_ = value;
      }
    }

    /// <summary>Field number for the "m_c_o_2_readings" field.</summary>
    public const int MCO2ReadingsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> _repeated_mCO2Readings_codec
        = pb::FieldCodec.ForMessage(18, global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading.Parser);
    private readonly pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> mCO2Readings_ = new pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> MCO2Readings {
      get { return mCO2Readings_; }
    }

    /// <summary>Field number for the "x_c_o_2_readings" field.</summary>
    public const int XCO2ReadingsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> _repeated_xCO2Readings_codec
        = pb::FieldCodec.ForMessage(26, global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading.Parser);
    private readonly pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> xCO2Readings_ = new pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> XCO2Readings {
      get { return xCO2Readings_; }
    }

    /// <summary>Field number for the "m_k_readings" field.</summary>
    public const int MKReadingsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> _repeated_mKReadings_codec
        = pb::FieldCodec.ForMessage(34, global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading.Parser);
    private readonly pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> mKReadings_ = new pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> MKReadings {
      get { return mKReadings_; }
    }

    /// <summary>Field number for the "x_k_readings" field.</summary>
    public const int XKReadingsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> _repeated_xKReadings_codec
        = pb::FieldCodec.ForMessage(42, global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading.Parser);
    private readonly pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> xKReadings_ = new pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Verra.Ccs.ExtensionSet.Modules.Vm0049.VariableReading> XKReadings {
      get { return xKReadings_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Formula3PercentCo2Mass);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Formula3PercentCo2Mass other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PercentCo2Mass, other.PercentCo2Mass)) return false;
      if(!mCO2Readings_.Equals(other.mCO2Readings_)) return false;
      if(!xCO2Readings_.Equals(other.xCO2Readings_)) return false;
      if(!mKReadings_.Equals(other.mKReadings_)) return false;
      if(!xKReadings_.Equals(other.xKReadings_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (percentCo2Mass_ != null) hash ^= PercentCo2Mass.GetHashCode();
      hash ^= mCO2Readings_.GetHashCode();
      hash ^= xCO2Readings_.GetHashCode();
      hash ^= mKReadings_.GetHashCode();
      hash ^= xKReadings_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (percentCo2Mass_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PercentCo2Mass);
      }
      mCO2Readings_.WriteTo(output, _repeated_mCO2Readings_codec);
      xCO2Readings_.WriteTo(output, _repeated_xCO2Readings_codec);
      mKReadings_.WriteTo(output, _repeated_mKReadings_codec);
      xKReadings_.WriteTo(output, _repeated_xKReadings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (percentCo2Mass_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PercentCo2Mass);
      }
      mCO2Readings_.WriteTo(ref output, _repeated_mCO2Readings_codec);
      xCO2Readings_.WriteTo(ref output, _repeated_xCO2Readings_codec);
      mKReadings_.WriteTo(ref output, _repeated_mKReadings_codec);
      xKReadings_.WriteTo(ref output, _repeated_xKReadings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (percentCo2Mass_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PercentCo2Mass);
      }
      size += mCO2Readings_.CalculateSize(_repeated_mCO2Readings_codec);
      size += xCO2Readings_.CalculateSize(_repeated_xCO2Readings_codec);
      size += mKReadings_.CalculateSize(_repeated_mKReadings_codec);
      size += xKReadings_.CalculateSize(_repeated_xKReadings_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Formula3PercentCo2Mass other) {
      if (other == null) {
        return;
      }
      if (other.percentCo2Mass_ != null) {
        if (percentCo2Mass_ == null) {
          PercentCo2Mass = new global::Verra.Ccs.ExtensionSet.DoubleValue();
        }
        PercentCo2Mass.MergeFrom(other.PercentCo2Mass);
      }
      mCO2Readings_.Add(other.mCO2Readings_);
      xCO2Readings_.Add(other.xCO2Readings_);
      mKReadings_.Add(other.mKReadings_);
      xKReadings_.Add(other.xKReadings_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (percentCo2Mass_ == null) {
              PercentCo2Mass = new global::Verra.Ccs.ExtensionSet.DoubleValue();
            }
            input.ReadMessage(PercentCo2Mass);
            break;
          }
          case 18: {
            mCO2Readings_.AddEntriesFrom(input, _repeated_mCO2Readings_codec);
            break;
          }
          case 26: {
            xCO2Readings_.AddEntriesFrom(input, _repeated_xCO2Readings_codec);
            break;
          }
          case 34: {
            mKReadings_.AddEntriesFrom(input, _repeated_mKReadings_codec);
            break;
          }
          case 42: {
            xKReadings_.AddEntriesFrom(input, _repeated_xKReadings_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (percentCo2Mass_ == null) {
              PercentCo2Mass = new global::Verra.Ccs.ExtensionSet.DoubleValue();
            }
            input.ReadMessage(PercentCo2Mass);
            break;
          }
          case 18: {
            mCO2Readings_.AddEntriesFrom(ref input, _repeated_mCO2Readings_codec);
            break;
          }
          case 26: {
            xCO2Readings_.AddEntriesFrom(ref input, _repeated_xCO2Readings_codec);
            break;
          }
          case 34: {
            mKReadings_.AddEntriesFrom(ref input, _repeated_mKReadings_codec);
            break;
          }
          case 42: {
            xKReadings_.AddEntriesFrom(ref input, _repeated_xKReadings_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VariableReading : pb::IMessage<VariableReading>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VariableReading> _parser = new pb::MessageParser<VariableReading>(() => new VariableReading());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VariableReading> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Verra.Ccs.ExtensionSet.Modules.Vm0049.Vm0049Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VariableReading() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VariableReading(VariableReading other) : this() {
      checkpointId_ = other.checkpointId_;
      checkpointVariableId_ = other.checkpointVariableId_;
      variableTemplateId_ = other.variableTemplateId_;
      variableTemplateVersion_ = other.variableTemplateVersion_;
      variableValue_ = other.variableValue_ != null ? other.variableValue_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VariableReading Clone() {
      return new VariableReading(this);
    }

    /// <summary>Field number for the "checkpoint_id" field.</summary>
    public const int CheckpointIdFieldNumber = 1;
    private string checkpointId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CheckpointId {
      get { return checkpointId_; }
      set {
        checkpointId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "checkpoint_variable_id" field.</summary>
    public const int CheckpointVariableIdFieldNumber = 2;
    private string checkpointVariableId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CheckpointVariableId {
      get { return checkpointVariableId_; }
      set {
        checkpointVariableId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "variable_template_id" field.</summary>
    public const int VariableTemplateIdFieldNumber = 3;
    private string variableTemplateId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VariableTemplateId {
      get { return variableTemplateId_; }
      set {
        variableTemplateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "variable_template_version" field.</summary>
    public const int VariableTemplateVersionFieldNumber = 4;
    private string variableTemplateVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VariableTemplateVersion {
      get { return variableTemplateVersion_; }
      set {
        variableTemplateVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "variable_value" field.</summary>
    public const int VariableValueFieldNumber = 5;
    private global::Verra.Ccs.ExtensionSet.DoubleValue variableValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Verra.Ccs.ExtensionSet.DoubleValue VariableValue {
      get { return variableValue_; }
      set {
        variableValue_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VariableReading);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VariableReading other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CheckpointId != other.CheckpointId) return false;
      if (CheckpointVariableId != other.CheckpointVariableId) return false;
      if (VariableTemplateId != other.VariableTemplateId) return false;
      if (VariableTemplateVersion != other.VariableTemplateVersion) return false;
      if (!object.Equals(VariableValue, other.VariableValue)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CheckpointId.Length != 0) hash ^= CheckpointId.GetHashCode();
      if (CheckpointVariableId.Length != 0) hash ^= CheckpointVariableId.GetHashCode();
      if (VariableTemplateId.Length != 0) hash ^= VariableTemplateId.GetHashCode();
      if (VariableTemplateVersion.Length != 0) hash ^= VariableTemplateVersion.GetHashCode();
      if (variableValue_ != null) hash ^= VariableValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CheckpointId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CheckpointId);
      }
      if (CheckpointVariableId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CheckpointVariableId);
      }
      if (VariableTemplateId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VariableTemplateId);
      }
      if (VariableTemplateVersion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(VariableTemplateVersion);
      }
      if (variableValue_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VariableValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CheckpointId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CheckpointId);
      }
      if (CheckpointVariableId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CheckpointVariableId);
      }
      if (VariableTemplateId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VariableTemplateId);
      }
      if (VariableTemplateVersion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(VariableTemplateVersion);
      }
      if (variableValue_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VariableValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CheckpointId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CheckpointId);
      }
      if (CheckpointVariableId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CheckpointVariableId);
      }
      if (VariableTemplateId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VariableTemplateId);
      }
      if (VariableTemplateVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VariableTemplateVersion);
      }
      if (variableValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VariableValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VariableReading other) {
      if (other == null) {
        return;
      }
      if (other.CheckpointId.Length != 0) {
        CheckpointId = other.CheckpointId;
      }
      if (other.CheckpointVariableId.Length != 0) {
        CheckpointVariableId = other.CheckpointVariableId;
      }
      if (other.VariableTemplateId.Length != 0) {
        VariableTemplateId = other.VariableTemplateId;
      }
      if (other.VariableTemplateVersion.Length != 0) {
        VariableTemplateVersion = other.VariableTemplateVersion;
      }
      if (other.variableValue_ != null) {
        if (variableValue_ == null) {
          VariableValue = new global::Verra.Ccs.ExtensionSet.DoubleValue();
        }
        VariableValue.MergeFrom(other.VariableValue);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CheckpointId = input.ReadString();
            break;
          }
          case 18: {
            CheckpointVariableId = input.ReadString();
            break;
          }
          case 26: {
            VariableTemplateId = input.ReadString();
            break;
          }
          case 34: {
            VariableTemplateVersion = input.ReadString();
            break;
          }
          case 42: {
            if (variableValue_ == null) {
              VariableValue = new global::Verra.Ccs.ExtensionSet.DoubleValue();
            }
            input.ReadMessage(VariableValue);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CheckpointId = input.ReadString();
            break;
          }
          case 18: {
            CheckpointVariableId = input.ReadString();
            break;
          }
          case 26: {
            VariableTemplateId = input.ReadString();
            break;
          }
          case 34: {
            VariableTemplateVersion = input.ReadString();
            break;
          }
          case 42: {
            if (variableValue_ == null) {
              VariableValue = new global::Verra.Ccs.ExtensionSet.DoubleValue();
            }
            input.ReadMessage(VariableValue);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
