// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vmd0056.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Verra.Ccs.ExtensionSet.Modules.Vmd0056 {

  /// <summary>Holder for reflection information generated from vmd0056.proto</summary>
  public static partial class Vmd0056Reflection {

    #region Descriptor
    /// <summary>File descriptor for vmd0056.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Vmd0056Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg12bWQwMDU2LnByb3RvEiZ2ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0Lm1vZHVs",
            "ZXMudm1kMDA1NkJTCiZ2ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0Lm1vZHVsZXMu",
            "dm1kMDA1NlABqgImVmVycmEuQ2NzLkV4dGVuc2lvblNldC5Nb2R1bGVzLlZt",
            "ZDAwNTZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
