// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vmd0058.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Verra.Ccs.ExtensionSet.Modules.Vmd0058 {

  /// <summary>Holder for reflection information generated from vmd0058.proto</summary>
  public static partial class Vmd0058Reflection {

    #region Descriptor
    /// <summary>File descriptor for vmd0058.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Vmd0058Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg12bWQwMDU4LnByb3RvEiZ2ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0Lm1vZHVs",
            "ZXMudm1kMDA1OCoxCgtTdG9yYWdlVHlwZRIOCgpnZW9sb2dpY2FsEAASEgoO",
            "c2FsaW5lX2FxdWlmZXIQAUJTCiZ2ZXJyYS5jY3MuZXh0ZW5zaW9uU2V0Lm1v",
            "ZHVsZXMudm1kMDA1OFABqgImVmVycmEuQ2NzLkV4dGVuc2lvblNldC5Nb2R1",
            "bGVzLlZtZDAwNThiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Verra.Ccs.ExtensionSet.Modules.Vmd0058.StorageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StorageType {
    [pbr::OriginalName("geological")] Geological = 0,
    [pbr::OriginalName("saline_aquifer")] SalineAquifer = 1,
  }

  #endregion

}

#endregion Designer generated code
