syntax = "proto3";

package verra.ccs.extensionSet.modules.vm0049;
import "verraCcsExtensionSet.proto";
option csharp_namespace = "Verra.Ccs.ExtensionSet.Modules.Vm0049";
option java_package = "verra.ccs.extensionSet.modules.vm0049";
option java_multiple_files = true;

message Formula3PercentCo2Mass{
    verra.ccs.extensionSet.DoubleValue percent_co2_mass = 1;
    repeated VariableReading m_c_o_2_readings = 2;
    repeated VariableReading x_c_o_2_readings = 3;
    repeated VariableReading m_k_readings = 4;
    repeated VariableReading x_k_readings = 5;
}

message VariableReading{
    string checkpoint_id = 1;
    string checkpoint_variable_id = 2;
    string variable_template_id = 3;
    string variable_template_version = 4;
    ccs.extensionSet.DoubleValue variable_value = 5;
}