// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vmd0057.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Verra.Ccs.ExtensionSet.Modules.Vmd0057 {

  /// <summary>Holder for reflection information generated from vmd0057.proto</summary>
  public static partial class Vmd0057Reflection {

    #region Descriptor
    /// <summary>File descriptor for vmd0057.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Vmd0057Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg12bWQwMDU3LnByb3RvEiBjY3MuZXh0ZW5zaW9uU2V0Lm1vZHVsZXMudm1k",
            "MDA1NyJbChBUcmFuc3BvcnRQcm9maWxlEkcKDnRyYW5zcG9ydF90eXBlGAEg",
            "ASgOMi8uY2NzLmV4dGVuc2lvblNldC5tb2R1bGVzLnZtZDAwNTcuVHJhbnNw",
            "b3J0VHlwZSpGCg1UcmFuc3BvcnRUeXBlEggKBFJvYWQQABIICgRSYWlsEAES",
            "DAoIUGlwZWxpbmUQAhIICgRTaGlwEAMSCQoFTWl4ZWQQBEJTCiZ2ZXJyYS5j",
            "Y3MuZXh0ZW5zaW9uU2V0Lm1vZHVsZXMudm1kMDA1N1ABqgImVmVycmEuQ2Nz",
            "LkV4dGVuc2lvblNldC5Nb2R1bGVzLlZtZDAwNTdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportProfile), global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportProfile.Parser, new[]{ "TransportType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TransportType {
    [pbr::OriginalName("Road")] Road = 0,
    [pbr::OriginalName("Rail")] Rail = 1,
    [pbr::OriginalName("Pipeline")] Pipeline = 2,
    [pbr::OriginalName("Ship")] Ship = 3,
    [pbr::OriginalName("Mixed")] Mixed = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  ///entity extension
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TransportProfile : pb::IMessage<TransportProfile>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransportProfile> _parser = new pb::MessageParser<TransportProfile>(() => new TransportProfile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransportProfile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.Vmd0057Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportProfile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportProfile(TransportProfile other) : this() {
      transportType_ = other.transportType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransportProfile Clone() {
      return new TransportProfile(this);
    }

    /// <summary>Field number for the "transport_type" field.</summary>
    public const int TransportTypeFieldNumber = 1;
    private global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType transportType_ = global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType TransportType {
      get { return transportType_; }
      set {
        transportType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransportProfile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransportProfile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransportType != other.TransportType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TransportType != global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road) hash ^= TransportType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TransportType != global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TransportType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TransportType != global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TransportType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TransportType != global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TransportType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransportProfile other) {
      if (other == null) {
        return;
      }
      if (other.TransportType != global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType.Road) {
        TransportType = other.TransportType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TransportType = (global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TransportType = (global::Verra.Ccs.ExtensionSet.Modules.Vmd0057.TransportType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
